import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const engineSource = readFileSync(
  resolve(process.cwd(), 'src/lib/snake-experience.ts'),
  'utf8',
);

describe('snake engine source contract', () => {
  it('drives linear burst state without defeat buttons', () => {
    expect(engineSource).toContain('renderBackground(');
    expect(engineSource).toContain('prepared: PreparedText');
    expect(engineSource).toContain('const BACKGROUND_TEXT_SIZE = 13;');
    expect(engineSource).toContain('const MOBILE_BACKGROUND_WORD_COUNT = 220;');
    expect(engineSource).toContain('const TABLET_BACKGROUND_WORD_COUNT = 520;');
    expect(engineSource).toContain('resolveBackgroundLayout(');
    expect(engineSource).toContain('avoidSnakeRadius');
    expect(engineSource).toContain('intersectsSnakeBody(');
    expect(engineSource).toContain('const count = 3 + Math.floor(random() * 4);');
    expect(engineSource).toContain('const looseWidth = 340 + random() * 220 + phrase.intensity * 54;');
    expect(engineSource).toContain('const laneOffset = index - (count - 1) / 2;');
    expect(engineSource).toContain('const lateral = laneOffset * (136 + random() * 32);');
    expect(engineSource).toContain('const vertical = (random() - 0.5) * 68 + ((index % 2) * 2 - 1) * 34;');
    expect(engineSource).toContain('const BURST_SWAY = 0.04;');
    expect(engineSource).toContain('const BURST_ECHO_OFFSET = 4;');
    expect(engineSource).toContain('type PreparedPhraseGroups = {');
    expect(engineSource).toContain('ko: PreparedPhrase[];');
    expect(engineSource).toContain('en: PreparedPhrase[];');
    expect(engineSource).toContain('const startWithEnglish = random() > 0.5;');
    expect(engineSource).toContain('const useEnglish = (index % 2 === 0) === startWithEnglish;');
    expect(engineSource).toContain('const pool = useEnglish ? preparedPhrases.en : preparedPhrases.ko;');
    expect(engineSource).toContain('function createBurstKeyframes(');
    expect(engineSource).toContain('keyframes: createBurstKeyframes(');
    expect(engineSource).toContain('function interpolateBurstFrames(');
    expect(engineSource).toContain('function computeViewportScale(');
    expect(engineSource).toContain('function getBackgroundWordCount(');
    expect(engineSource).toContain('viewportScale');
    expect(engineSource).toContain('gameOverAt');
    expect(engineSource).toContain('gameOverOrigin');
    expect(engineSource).toContain('function renderGameOverOverlay(');
    expect(engineSource).toContain("const title = '퇴근';");
    expect(engineSource).toContain("const subtitle = 'get off work';");
    expect(engineSource).toContain('ctx.fillText(title, centerX, centerY + scoreSize * 0.88);');
    expect(engineSource).toContain('ctx.fillText(subtitle, centerX, centerY + scoreSize * 1.08);');
    expect(engineSource).toContain('if (state.over) {');
    expect(engineSource).toContain('renderSnake(ctx, state.snake, state.cellSize, worldNow);');
    expect(engineSource).toContain('renderGameOverOverlay(');
    expect(engineSource).toContain("score.textContent = state.over ? '' : `length ${state.score}`;");
    expect(engineSource).toContain("event.key === 'Enter' || event.key === ' '");
    expect(engineSource).toContain('paused: boolean;');
    expect(engineSource).toContain('state.paused = !state.paused;');
    expect(engineSource).toContain('type SwipeState = {');
    expect(engineSource).toContain('pointerId: number;');
    expect(engineSource).toContain('pointerType: string;');
    expect(engineSource).toContain('function getSwipeDirection(');
    expect(engineSource).toContain("event.pointerType === 'mouse'");
    expect(engineSource).toContain("root.addEventListener('pointerdown', handlePointerDown);");
    expect(engineSource).toContain("root.addEventListener('pointerup', handlePointerUp);");
    expect(engineSource).toContain("root.addEventListener('pointercancel', handlePointerCancel);");
    expect(engineSource).toContain('const restartOnTap = state.over');
    expect(engineSource).toContain('state.gameOverAt = now');
    expect(engineSource).toContain('function drawDotCell(');
    expect(engineSource).toContain('drawDotCell(ctx, x, y, size);');
    expect(engineSource).toContain('function drawTakeoutCupGlyph(');
    expect(engineSource).toContain('drawTakeoutCupGlyph(ctx, x, y, size);');
    expect(engineSource).toContain('const FOOD_DOT_INSET = 4;');
    expect(engineSource).toContain('const SNAKE_DOT_INSET = 4;');
    expect(engineSource).toContain('state.lockUntil = now + playfieldConfig.burstLockMs');
    expect(engineSource).not.toContain('document.createElement(\'button\')');
    expect(engineSource).not.toContain('overlay.append(');
    expect(engineSource).not.toContain('renderGameOverBackdrop(');
    expect(engineSource).not.toContain('foldGlow');
    expect(engineSource).not.toContain('foldBand');
    expect(engineSource).not.toContain('drawCatFace');
    expect(engineSource).not.toContain('shimmerUntil');
    expect(engineSource).not.toContain('shimmerOrigin');
    expect(engineSource).not.toContain('createRadialGradient');
    expect(engineSource).not.toContain('function computeFieldFoldState(');
    expect(engineSource).not.toContain('Math.cos(angle) * spread');
    expect(engineSource).not.toContain('Math.sin(angle) * spread');
  });
});
